// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

// CreateUser inserts a new user and returns it
func (q *Queries) CreateUser(ctx context.Context, name string, dob time.Time) (User, error) {
	query := `INSERT INTO users (name, dob) VALUES ($1, $2) RETURNING id, name, dob`
	row := q.db.QueryRow(ctx, query, name, dob)
	var user User
	err := row.Scan(&user.ID, &user.Name, &user.Dob)
	return user, err
}

// GetUserByID finds a user by their ID
func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	query := `SELECT id, name, dob FROM users WHERE id = $1`
	row := q.db.QueryRow(ctx, query, id)
	var user User
	err := row.Scan(&user.ID, &user.Name, &user.Dob)
	return user, err
}

// ListUsers returns all users ordered by ID
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	query := `SELECT id, name, dob FROM users ORDER BY id`
	rows, err := q.db.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var user User
		if err := rows.Scan(&user.ID, &user.Name, &user.Dob); err != nil {
			return nil, err
		}
		users = append(users, user)
	}
	return users, nil
}

// UpdateUser updates a user and returns the updated user
func (q *Queries) UpdateUser(ctx context.Context, name string, dob time.Time, id int32) (User, error) {
	query := `UPDATE users SET name = $1, dob = $2 WHERE id = $3 RETURNING id, name, dob`
	row := q.db.QueryRow(ctx, query, name, dob, id)
	var user User
	err := row.Scan(&user.ID, &user.Name, &user.Dob)
	return user, err
}

// DeleteUser removes a user by ID
func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	query := `DELETE FROM users WHERE id = $1`
	_, err := q.db.Exec(ctx, query, id)
	return err
}
